### ISSUE TITLE
On Win8.1 - Не собирается приложение (webpack), выдает ошибку

### ISSUE THREAD

**Issue by Semalexa** [Aidbox/sample-spa#6]
Не собирается приложение (webpack), выдает ошибку:

ERROR in ./coffee/app.coffee
Module not found: Error: Cannot resolve 'file' or 'directory' ../../bower_components/angular/angular.js in D:\Work\aidbox\sample/src\coffee
 @ ./coffee/app.coffee 3:0-54

**Comment by niquola** [comment]
I think problem with Windows pathes. See how node abstract work with file system

**Comment by Aitem** [comment]
Мы отказались от Webpack в данном приложении и перешли на CDN
